"""empty message

Revision ID: f918de241c75
Revises: 990d1ebb3d8e
Create Date: 2023-06-26 13:27:59.546279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f918de241c75'
down_revision = '990d1ebb3d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('day_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'day_created')
    # ### end Alembic commands ###
